services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: notifications
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - '2181:2181'

  # app:
  #   container_name: app
  #   build: .
  #   command: pnpm dev
  #   volumes:
  #     - ./:/usr/src/app
  #   working_dir: /usr/src/app
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     DATABASE_URL: 'postgresql://prisma:prisma@postgres:5432/notifications_dev'
  #     KAFKA_BROKER: 'kafka:9092'
  #   depends_on:
  #     - postgres
  #     - kafka

volumes:
  db_data:
