apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgrespassword@postgres:5432/notifications"
  API_TOKEN: "mySecretToken"
  KAFKA_BROKER: "kafka1:9092"