apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
      - name: notification-api
        image: yourregistry/notifications_api:latest
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-api
spec:
  type: ClusterIP
  selector:
    app: notification-api
  ports:
  - port: 80
    targetPort: 3000
